apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80  # Port exposed externally
      targetPort: 80  # Port on the container
  type: NodePort  # Change to LoadBalancer if needed, NodePort for minikube

