name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      # ... other steps remain the same ...
      - name: Calculate new version and create tag
        id: tag_version
        run: |
          # ... existing script to calculate new_tag ...
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          # Set the new_tag output for other jobs to use
          echo "::set-output name=new_tag::$new_tag"

  build-and-push-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          new_tag=${{ needs.build.outputs.new_tag }}
          if [ -z "$new_tag" ]; then
            echo "New tag is empty. Please check the tag calculation step."
            exit 1
          fi
          docker build -t idan5567/k8s_test:$new_tag .
          docker push idan5567/k8s_test:$new_tag



